baseurl = "https://www.nabarun.in/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Nabarun Pal"
title = "Nabarun Pal"

theme = "hugo-split-theme"

enableRobotsTXT = true

copyright = "&copy;2020 <a href='https://creativecommons.org/licenses/by-nc-sa/2.0/'>CC-BY-NC-SA</a> Nabarun Pal"

[params]
author = "Nabarun Pal"
description = "Infrastructure. Polyglot. Engineer. Open Source."
dateformat = "Jan 2, 2006"
shareImage = "img/deep.jpg"
twitterHandle = "theonlynabarun"

[params.visual]
[params.visual.image]
    enable = true
    file = "img/deep.jpg"
    position = "center center"

[[params.links]]
[params.links.list1]
    heading = ""

    [[params.links.list1.link]]
    text = "Blog"
    url = "//blog.naba.run"

    [[params.links.list1.link]]
    text = "GitHub"
    url = "//github.com/palnabarun"

    [[params.links.list1.link]]
    text = "Keybase"
    url = "//keybase.io/nabarun"

[[params.links]]
[params.links.list2]
    heading = ""

    [[params.links.list2.link]]
    text = "Twitter"
    url = "//twitter.com/theonlynabarun"

    [[params.links.list2.link]]
    text = "LinkedIn"
    url = "//linkedin.com/in/palnabarun"

    [[params.links.list2.link]]
    text = "Email"
    url = "mailto:hey@naba.run"

[[params.links]]
[params.links.list3]
    heading = ""

    [[params.links.list3.link]]
    text = "Talks"
    url = "/talks/"

    [[params.links.list3.link]]
    text = "Resume"
    url = "/share/resume.pdf"
