## Basic Configuration

baseurl = "https://www.nabarun.in/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Nabarun Pal"
title = "Nabarun Pal"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Nabarun Pal"
intro = "Software Engineer && {Systems,Open Source} Enthusiast <br/> Full Time Pythonista && Budding Gopher"
description = "Infrastructure and Site Reliability <a href='//www.rorodata.com' target='_blank'>@rorodata</a> | John Hunter Matplotlib Summer Fellow <a href='//www.numfocus.org' target='_blank'>@numfocus</a> <br/> Google Udacity India Scholar | Graduate from IITRoorkee"
authorimage = "pp.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Landing Page for Nabarun Pal"
keywords = "developer,blog,nabarun,pal,software,engineer"

## Social Accounts
[params.social]
github = "palnabarun"
gitlab = "palnabarun"
#instagram = "<username>"
#xing = "<username>"
linkedin = "palnabarun"
twitter = "_palnabarun"
#facebook = "<username>"
google = "pal.nabarun95"
stackoverflow = "nabarun-pal"
email = "pal@nabarun.in"
keybase = "nabarun"
gpg = "5766 AE48 2884 5256 325B DA6E 611D 5079 D826 B150"

## Extras
[params.extra]
#copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
copyright = "© 2017-2019 Nabarun Pal <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png'/></a>"
poweredby = true
highlightjs = true
displayrssicon = false

[[menu.main]]
    name = "talks"
    identifier = "talks"
    weight = 200
    url = "/talks/"
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 300
    url = "https://blog.nabarun.in/"
[[menu.main]]
    name = "cv"
    identifier = "cv"
    weight = 100
    url = "/cv/"
